export const IPC = {
  ping: 'app:ping',
  configLanguage: 'config:language',
  configLanguagePath: 'config:languagePath',
  configUser: 'config:user',
  configUserSave: 'config:userSave',
  configUserPath: 'config:userPath',
  appInstallCommandLine: 'app:installCommandLine',
  fileOpenDialog: 'file:openDialog',
  fileRead: 'file:read',
  fileSave: 'file:save',
  fileSaveAsDialog: 'file:saveAsDialog',
  fileCreate: 'file:create',
  fileCreateDirectory: 'file:createDirectory',
  fileDelete: 'file:delete',
  fileCopy: 'file:copy',
  gitBaseline: 'git:baseline',
  gitStatus: 'git:status',
  workspaceOpenFolderDialog: 'workspace:openFolderDialog',
  workspaceCurrentFolder: 'workspace:currentFolder',
  workspaceListTree: 'workspace:listTree',
  workspaceSearch: 'workspace:search',
  workspaceChanged: 'workspace:changed',
  windowZoomIn: 'window:zoomIn',
  windowZoomOut: 'window:zoomOut',
  windowZoomReset: 'window:zoomReset',
  windowCloseRequested: 'window:closeRequested',
  windowCloseProceed: 'window:closeProceed',
  windowCloseCancel: 'window:closeCancel',
  dialogUnsavedChanges: 'dialog:unsavedChanges',
  menuCommand: 'menu:command',
  themeOsChanged: 'theme:osChanged',
  lspStart: 'lsp:start',
  lspStop: 'lsp:stop',
  lspToServer: 'lsp:toServer',
  lspFromServer: 'lsp:fromServer',
  lspServerExit: 'lsp:serverExit',
  lspServerStderr: 'lsp:serverStderr',
  lspServerLog: 'lsp:serverLog',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
