export const IPC = {
  ping: 'app:ping',
  configLanguage: 'config:language',
  configLanguagePath: 'config:languagePath',
  appInstallCommandLine: 'app:installCommandLine',
  fileOpenDialog: 'file:openDialog',
  fileRead: 'file:read',
  fileSave: 'file:save',
  fileSaveAsDialog: 'file:saveAsDialog',
  gitBaseline: 'git:baseline',
  workspaceOpenFolderDialog: 'workspace:openFolderDialog',
  workspaceCurrentFolder: 'workspace:currentFolder',
  workspaceListTree: 'workspace:listTree',
  workspaceChanged: 'workspace:changed',
  windowZoomIn: 'window:zoomIn',
  windowZoomOut: 'window:zoomOut',
  windowZoomReset: 'window:zoomReset',
  menuCommand: 'menu:command',
  themeOsChanged: 'theme:osChanged',
  lspStart: 'lsp:start',
  lspStop: 'lsp:stop',
  lspToServer: 'lsp:toServer',
  lspFromServer: 'lsp:fromServer',
  lspServerExit: 'lsp:serverExit',
  lspServerStderr: 'lsp:serverStderr',
  lspServerLog: 'lsp:serverLog',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
